### PR TITLE
fix: refs for react v16 needs to be a function - this.refs is deprecated 

### PR DESCRIPTION
**Pull request by ghost**
Uncaught Error: Element ref was specified as a string (ReactPasswordStrength-input) but no owner was set. You may have multiple copies of React loaded. (details: https://fb.me/react-refs-must-have-owner).

### CODE REVIEW

**Comment by mmw** [comment]
Can you link to where `this.refs` is deprecated in v16? Why does using it as a fn work if its deprecated? The details you linked to suggest that you have a problem in your env not in the tool.

**Comment by ghost** [comment]
Hi, here is the link and screenshot of the section on the docs.

You are correct, I was on a very old version of yarn which caused the issue, but the refs issue can be updated. 

Thanks for the plugin! Makes life much easier 👯 

https://reactjs.org/docs/refs-and-the-dom.html
screen shot 2017-10-31 at 10 30 38 pm

**Comment by mmw** [comment]
Cool, thanks for the quick reply (and sorry for taking so long). I dont think I can merge this in the current state though, if Im not mistaken this change will break the example app so that would need to be updated. If you have time plz fix, otherwise I'll make all the fixes when I address issue #54

**Comment by mmw** [comment]
And https://github.com/mmw/react-password-strength#functions will need to be updated as well

**Comment by ghost** [comment]
Great, I will see if I can do in the next 24 hours for you

**Comment by mmw** [comment]
Thanks, and looking quickly right now I think Im wrong. If you can please confirm that example app still works with this change

**Review by mmw — APPROVED** [review]
checked locally, example app works as expected. thanks for the PR

**Pull request merged**
