### PR TITLE
Render as something else than input

### PR DESCRIPTION
**Pull request by zaratan**
Add the capability to render as something than an input. For example a `Input` or a `Field.Input` from https://react.semantic-ui.com/elements/input

### CODE REVIEW

**Comment by mmw** [comment]
Im sorry, Ive been swamped lately, I will take a look at this PR soon

**Comment by zaratan** [comment]
Don't worry. I created a separate npm package so I can use it while this PR is still open.

**Comment by mmw** [comment]
@denispasin I think this is a pretty edge case feature you're supporting and would prefer not to support it because it will increase the complexity of the app and I would need more comprehensive testing coverage.

If you feel strongly about this I would invite you ton continue your fork/separate npm package. This tool isnt terribly compelx, it's just a wrapper for `zxcvbn` so if you need it for something more than just a simple input I would suggest using something else or writing it custom for your project.

**Comment by zaratan** [comment]
I'm fine with this. I can definitely live with my fork :) Thx for looking inside my PR.

**Pull request closed without merging**
